events {}

http {

  server {
    listen 80;
    server_name localhost;
    location / {
      proxy_pass http://172.17.0.1:8080;
      proxy_set_header Host $host;
    }
  }

  server {
    listen 80;
    server_name gitea.lab;
    location / {
      proxy_pass http://gitea:3000;
      proxy_set_header Host $host;
    }
  }

  server {
    listen 80;
    server_name nexus.lab;
    location / {
      proxy_pass http://nexus:8081;
      proxy_set_header Host $host;
    }
  }

  server {
    listen 80;
    server_name sonar.lab;
    location / {
      proxy_pass http://sonarqube:9000;
      proxy_set_header Host $host;
    }
  }

}